### ISSUE TITLE
Setup Automated Documentation with GitHub Actions

### ISSUE THREAD

**Issue by Dhairya-Chheda** [Dhairya-Chheda/wix-freaks-central-lib#2]
## GitHub Actions Setup for Documentation

Create the following files:

### 1. `.github/workflows/documentation.yml`:
```yaml
name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install -g jsdoc
        npm install better-docs

    - name: Generate documentation
      run: |
        jsdoc -c jsdoc.json

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
```

### 2. `jsdoc.json`:
```json
{
  "source": {
    "include": ["functions", "patterns", "components"],
    "includePattern": ".js$",
    "excludePattern": "(node_modules/|docs)"
  },
  "plugins": ["plugins/markdown", "better-docs/component"],
  "templates": {
    "better-docs": {
      "name": "Wix Freaks Component Library"
    }
  },
  "opts": {
    "destination": "./docs",
    "recurse": true,
    "readme": "README.md"
  }
}
```

## Steps to Implement:
1. Create the `.github/workflows` directory
2. Add the `documentation.yml` file
3. Add the `jsdoc.json` configuration file
4. Enable GitHub Pages in repository settings
5. Test the workflow with a sample documentation commit
