### ISSUE TITLE
Setup Validation Workflow for Metadata Files

### ISSUE THREAD

**Issue by Dhairya-Chheda** [Dhairya-Chheda/wix-freaks-central-lib#4]
## Metadata Validation Workflow

Create a GitHub Action to validate metadata files:

### 1. `.github/workflows/validate-metadata.yml`:
```yaml
name: Validate Metadata

on:
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install ajv

    - name: Validate JSON files
      run: node .github/scripts/validate-metadata.js

```

### 2. Create validation script
Create `.github/scripts/validate-metadata.js`:
```javascript
const Ajv = require('ajv');
const fs = require('fs');
const path = require('path');
const ajv = new Ajv();

// Metadata schema
const schema = {
  type: 'object',
  required: ['name', 'category', 'type', 'description', 'dependencies'],
  properties: {
    name: { type: 'string' },
    category: { type: 'string' },
    type: { type: 'string' },
    description: { type: 'string' },
    dependencies: {
      type: 'array',
      items: { type: 'string' }
    },
    usage: {
      type: 'object',
      properties: {
        setup: { type: 'string' },
        examples: {
          type: 'array',
          items: { type: 'string' }
        }
      }
    }
  }
};

// Validation function
const validate = ajv.compile(schema);

// Walk through directories
function validateDirectory(dir) {
  const files = fs.readdirSync(dir);
  
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    
    if (stat.isDirectory()) {
      validateDirectory(filePath);
    } else if (file.endsWith('metadata.json')) {
      const data = JSON.parse(fs.readFileSync(filePath));
      const valid = validate(data);
      
      if (!valid) {
        console.error(`Validation failed for ${filePath}`);
        console.error(validate.errors);
        process.exit(1);
      }
    }
  });
}

// Start validation
validateDirectory('.');
```

## Steps to Implement:

1. Create the validation workflow file
2. Create the validation script
3. Add to CI/CD pipeline
4. Test with sample metadata files

## Additional Considerations:

1. Add custom validation rules for:
   - Valid Wix dependencies
   - Performance metrics
   - Security requirements

2. Add reporting:
   - Generate validation reports
   - Create GitHub check annotations
   - Send notifications for failures

3. Add automatic fixing capabilities:
   - Format JSON files
   - Add missing required fields with defaults
   - Update dependencies list
